### ISSUE TITLE
Warning: invalid conversion from 'const CustomClass1*' to 'CustomClass1*' [-fpermissive]

### ISSUE THREAD

**Issue by GitMoDu** [wizard97/Embedded_RingBuf_CPP#10]
I get this warning whenever use a class in the buffer. Things still work, not sure if it's something to look into. Code to reproduce the issue:

```
class CustomClass1
{
public:
	CustomClass1() {}
	uint8_t GetId() { return 0; }
};

RingBufCPP<CustomClass1, 10> TestCustomBuffer;

void DoSomethingWithBuffer()
{
    uint8_t Id = TestCustomBuffer.peek(0)->GetId();
}
```

**Comment by wizard97** [comment]
Can you double check you are on the newest version, I believe this issue was fixed a while ago:
https://github.com/wizard97/Embedded_RingBuf_CPP/commit/b6c3c2ea165f51bdc34528ac130d33454f5e0072

**Comment by GitMoDu** [comment]
Forgot to mention, I am on the Dev branch and indeed, that const keyword is there.

**Comment by GitMoDu** [comment]
I've taken the liberty to do a pull request on this issue.

**Comment by GitMoDu** [comment]
Fixed in https://github.com/wizard97/Embedded_RingBuf_CPP/pull/11
