### ISSUE TITLE
Not actually a ring buffer

### ISSUE THREAD

**Issue by bugadani** [wizard97/Embedded_RingBuf_CPP#12]
So I was looking for a simple ring buffer to save me some time and I stumbled upon this project. My main issue is that the name is a misnomer: a ring buffer should be a fifo with a max size (good so far) but one that discards old elements if it's full. The current implementation is a simple FIFO, not an actual ring buffer.

**Comment by JensGrabner** [comment]
This is the same here: https://www.embedded.com/electronics-blogs/embedded-round-table/4419407/The-ring-buffer  ...  This FIFO works fine in my project. "This queue has a first-in-first-out (FIFO) data characteristic."

**Comment by bugadani** [comment]
True, but a ring buffer overwrites the oldest data if it gets full - this behaviour is what makes it a "ring" buffer instead of a queue. Ring, meaning the write pointer overflows freely (i.e. goes around a ring) when adding elements. From your link: "The ring buffer is a circular software queue" - granted, it's not explained what they mean by "circular". A circular buffer retains the newest items and drops the oldest, this one one the other hand will not allow you to overwrite old items, instead "drops" the newer ones.

I'm not saying that this is not a fine library. It is. But it is not called what it is and that mislead me.

**Comment by wizard97** [comment]
github.com/wizard97/Embedded_RingBuf_CPP/pull/11/commits/96e0766feb1335ac03a756f37726651394df2bbc

**Comment by wizard97** [comment]
Also from that link:
There are two methods which handle this case. They are to drop the latest data or to overwrite the oldest data. Either style may be implemented. In our case, I will use the drop latest incoming data method.

**Comment by bugadani** [comment]
Very well, thanks for the insight. I guess I'm wrong and in this case, circular refers to the implementation and not the higher level operation. Thanks for clearing up the motivation behind a design choice. As per the dev branch: you are free to mark this issue as invalid, or already fixed. Thanks for the link to the patch (although personally I would have made it so one can select the overwrite behavior in the constructor, but that's just me).

Have fun creating!

**Comment by wizard97** [comment]
Hi,

No worries! Glad we got it figured out. I do actually agree it is much cleaner to have to the overwrite flag set in either the constructor or as a template argument, then get rid of the addForce() funcion. If you were to implement this, and create a pull request I would definitely accept it.
