### ISSUE TITLE
Library not found in Arduino Library Manager

### ISSUE THREAD

**Issue by descampsa** [wizard97/Embedded_RingBuf_CPP#2]
I can not find this library in the Arduino Library Manager, only the C RingBuffer library.
Not a problem for me, but you say in your readme that it is available in the Manager.

By the way, the fact that both C and C++ libraries have the same header filename make them impossible to install simultaneously. Maybe this is the cause of the problem, if the library manager detect the conflict?

**Comment by wizard97** [comment]
Hi,

Thanks for letting me know. I think I forgot to add it... I opened an issue on the Arduino GitHub to get it added. It should be available within the next day.

As for the header file name, I changed this ones to `RingBufCPP.h` to avoid conflicts with the C version: `RingBuf.h`.

Thanks again,
Aaron
