### ISSUE TITLE
Tag 1.2.0

### ISSUE THREAD

**Issue by Michel-Haber** [wizard97/Embedded_RingBuf_CPP#23]
@wizard97 could you please bump the master library version and tag it?
The add() API changed, but the change was not released.

**Comment by wizard97** [comment]
All set, thanks! [v1.2](https://github.com/wizard97/Embedded_RingBuf_CPP/releases/tag/1.2)

**Comment by Michel-Haber** [comment]
@wizard97 sorry I should have mentioned:
library.properties is still at 1.1

**Comment by wizard97** [comment]
Oops, updated: https://github.com/wizard97/Embedded_RingBuf_CPP/releases/tag/1.3
