### ISSUE TITLE
library.properties nearly identical to the C version

### ISSUE THREAD

**Issue by matthijskooijman** [wizard97/Embedded_RingBuf_CPP#5]
In particular the url field points to https://github.com/wizard97/ArduinoRingBuffer and the description is identical to that one, making me suspect that both libraries in the Arduino library are in fact duplicates of the same version.

**Comment by wizard97** [comment]
Oops, classic copy and paste mistake. The C++ version was created from the C version, so there are little remnants left over.

Feel free to fork it, fix it, and submit a pull request.

**Comment by matthijskooijman** [comment]
Willdo! I have some other changes pending to allow adding/removing elements from either end, so it can be used as  LIFO as well as a FIFO (though, over the course of the afternoon, I actually think I removed the need for these features in my code again :-p). I'll submit a PR for all that combined, might not be today though :-)

**Comment by wizard97** [comment]
Fantastic, I'll look for your pull request! If you don't mind can you make the changes to the dev branch?
